### ISSUE TITLE
Tighten up security and authentication

### ISSUE THREAD

**Issue by billgeo** [linz/QGIS-AIMS-Plugin#95]
Would be good to tighten up security and authentication if possible. e.g. not store plain text passwords in users credential stores and at least use hashed passwords. Leave this as a low priority for now until full security risk review has been done.

**Comment by dwsilk** [comment]
Security risk assessment workshop on 06/07/2016

**Comment by billgeo** [comment]
Spoke with It security and we should be at least hashing any passwords stored in user file, so let's do that as high priority and any further can be done later. 

See this for more info https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac

**Comment by josephramsay** [comment]
password hashing has been implemented on dev, needs to be tested

**Comment by Deb-Jones** [comment]
@billgeo @josephramsay  how does this get tested?

**Comment by billgeo** [comment]
If you can login successfully, you can consider it tested.

**Comment by dcleggnz** [comment]
@billgeo The login working is a regression test that verifies the file is able to be used to login correctly. Can it also be verified someone has opened the hashed file and ensured the usernames and passwords held within are not human readable ie the hash worked?

**Comment by ghost** [comment]
Can be done manually. Since tomcat-users (where the hashed pwds are stored) is owned by the tomcat user, scripting a test to read this potentially adds another layer of insecurity

**Comment by billgeo** [comment]
@josephramsay - This issue was for the QGIS plugin or application to not store plain text passwords. I believe they were caching passwords so users wouldn't need to enter it everytime? The tomcat task is covered in the another issue.

Can someone confirm that QGIS password cache is hashed?

**Comment by ghost** [comment]
They're the same issue, we can't do one without the other. 
On dev server side passwords are hashed. In the dev cache, any logins prior to the changeover probably won't be. Unless the server has been restarted. On the client, when the plugin gets reloaded any old pwds should get flushed. Awaiting testing

**Comment by billgeo** [comment]
Okay, this can be closed here if nothing for qgis plug in to do.

**Comment by billgeo** [comment]
AS discussed @SPlanzer, please look into using Windows/Linux Keyrings or user env. variables or similar to avoid using passwords stored in plaintext.

**Comment by SPlanzer** [comment]
Plan to user the users AD password by getting this via the python getpass library.

When the user 'Digests' their password and it is added to the tomcat-users.xml they would enter their AD password.

The down side to this however is that rather than the user having to find someone to su onto to the app server once to digest and update their password, this would have to be updated in the tomcat-users.xml every three months

**Comment by josephramsay** [comment]
Wrapped an AES cipher around the config file so pwd isn't saved as plaintext but recovery is trivial
user(text) -> config.enc(###) -> config.dec(text) -> HTTP -> md5.hash(text) -> tomcat.auth(###)

**Comment by billgeo** [comment]
Hi @josephramsay, two questions  as I need to run this past IT security. 
- [ ] Can you set the key length to 256?
- [ ] Where is the key stored? In the plugin code?

**Comment by ghost** [comment]
This is just the illusion of security but it does save us from having to store the user password in plaintext in the config file. Key length doesn't matter (FYI its 32 and no, that's the longest) because its a cipher not encryption and we're not doing two party encryption with pre-distributed keys. We're using a predefined key in the code and a IV (salt) using the system username and some padding. Because we have to send the password over HTTP as plaintext so have to de/encrypt in the code, anything we do client side is kinda pointless.

**Comment by ghost** [comment]
@splanzer don't worry about a user dialog, we can detect a non ciphered password and convert those as needed

**Comment by billgeo** [comment]
Have let IT security know. So closing for now.
